export const cards = [
    {
        id: 1,
        title: "chilvdren",
        desc: "rsfbberbrbrb4t",
        img: "./3dimage.jpg",
    },
    {
        id: 2,
        title: "tjetjetjerj",
        desc: "rt4tb4t",
        img: "./3dimage.jpg",
    },
    {
        id: 3,
        title: "tjetjetjerj",
        desc: "rt4tb4t",
        img: "./3dimage.jpg",
    },
    {
        id: 4,
        title: "tjetjetjerj",
        desc: "rt4tb4t",
        img: "./3dimage.jpg",
    },
    {
        id: 5,
        title: "tjetjetjerj",
        desc: "rt4tb4t",
        img: "./3dimage.jpg",
    },
    {
        id: 6,
        title: "tjetjetjerj",
        desc: "rt4tb4t",
        img: "./3dimage.jpg",
    },
    {
        id: 7,
        title: "tjetjetjerj",
        desc: "rt4tb4t",
        img: "./3dimage.jpg",
    },
    {
        id: 8,
        title: "tjetjetjerj",
        desc: "rt4tb4t",
        img: "./3dimage.jpg",
    },
    {
        id: 9,
        title: "tjetjetjerj",
        desc: "rt4tb4t",
        img: "./3dimage.jpg",
    },
    {
        id: 10,
        title: "tjetjetjerj",
        desc: "rt4tb4t",
        img: "./3dimage.jpg",
    },

];

export const gigs = [
    {
        id: 1,
        img: "./3dprint.png",
        pp: "./3dprint.png",
        desc: "gig1",
        price: 49,
        star: 5,
        username:"Ravindu Madushan" ,
    },
    {
        id: 2,
        img: "./3dprint.png",
        pp: "./3dprint.png",
        desc: "gig2",
        price: 49,
        star: 5,
        username:"Ravindu Madushan" ,
    },
    {
        id: 3,
        img: "./3dprint.png",
        pp: "./3dprint.png",
        desc: "gig3",
        price: 49,
        star: 5,
        username:"Ravindu Madushan" ,
    },
    {
        id: 4,
        img: "./3dprint.png",
        pp: "./3dprint.png",
        desc: "gig4",
        price: 49,
        star: 5,
        username:"Ravindu Madushan" ,
    },
    {
        id: 5,
        img: "./3dprint.png",
        pp: "./3dprint.png",
        desc: "gig5",
        price: 49,
        star: 5,
        username:"Ravindu Madushan" ,
    },
    {
        id: 6,
        img: "./3dprint.png",
        pp: "./3dprint.png",
        desc: "gig6",
        price: 49,
        star: 5,
        username:"Ravindu Madushan" ,
    },
    {
        id: 7,
        img: "./3dprint.png",
        pp: "./3dprint.png",
        desc: "gig7",
        price: 49,
        star: 5,
        username:"Ravindu Madushan" ,
    },
    {
        id: 8,
        img: "./3dprint.png",
        pp: "./3dprint.png",
        desc: "gig8",
        price: 49,
        star: 5,
        username:"Ravindu Madushan" ,
    },
    {
        id: 9,
        img: "./3dprint.png",
        pp: "./3dprint.png",
        desc: "gig9",
        price: 49,
        star: 5,
        username:"Ravindu Madushan" ,
    },
    {
        id: 10,
        img: "./3dprint.png",
        pp: "./3dprint.png",
        desc: "gig10",
        price: 49,
        star: 5,
        username:"Ravindu Madushan" ,
    },
     {
        id: 11,
        img: "./3dprint.png",
        pp: "./3dprint.png",
        desc: "gig11",
        price: 49,
        star: 5,
        username:" Ravindu Madushan" ,
    },
      {
        id: 12,
        img: "./3dprint.png",
        pp: "./3dprint.png",
        desc: "gig12",
        price: 49,
        star: 5,
        username:"Ravindu Madushan" ,
    },
]
